# Change baseurl before deploy
baseurl = "https://dowithsudo.com"
languageCode = "en-us"
title = "Practical Sysadmin & Network Notes"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

[pagination]
pagerSize = 5

[services]
  [services.googleAnalytics]
    id = 'G-H0MSX0M2D2'

[privacy]
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = true

#googleAnalytics = "G-H0MSX0M2D2'"